version: '3.8'

services:
  app:
    build:
      context: .
    container_name: foodia
    volumes:
      - app_logs:/app/logs
    depends_on:
      - db
    ports:
      - "3000:3000"
    networks:
      - backend

  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
    networks:
      - backend

networks:
  backend:
    driver: bridge


volumes:
  postgres_data:
  app_logs: