name: Deploy to Production

on:
  workflow_run:
    workflows: ["Go CD"]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/backend
            
            # Pull latest Docker image
            docker pull ${{ secrets.DOCKER_USERNAME }}/go-starter:latest
            
            cat > config.yaml << EOF
            # Database configuration
            DB_USER: ${{ secrets.DB_USER }}
            DB_NAME: ${{ secrets.DB_NAME }}
            DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
            DB_PORT: ${{ secrets.DB_PORT }}
            DB_HOST: ${{ secrets.DB_HOST }}

            # JWT and AES Keys
            JWT_SECRET: ${{ secrets.JWT_SECRET }}
            AES_KEY: ${{ secrets.AES_KEY }}

            # Mailing configuration
            APP_URL: ${{ secrets.APP_URL }}
            SMTP_HOST: ${{ secrets.SMTP_HOST }}
            SMTP_PORT: ${{ secrets.SMTP_PORT }}
            SMTP_SENDER_NAME: "${{ secrets.SMTP_SENDER_NAME }}"
            SMTP_AUTH_EMAIL: ${{ secrets.SMTP_AUTH_EMAIL }}
            SMTP_AUTH_PASSWORD: ${{ secrets.SMTP_AUTH_PASSWORD }}

            # Midtrans configuration
            CLIENT_KEY: "${{ secrets.CLIENT_KEY }}"
            SERVER_KEY: "${{ secrets.SERVER_KEY }}"
            IsProd: ${{ secrets.IS_PROD }}

            # AWS S3 configuration
            AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
            AWS_S3_REGION: ${{ secrets.AWS_S3_REGION }}
            AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
            AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}

            # AI Model Service
            AI_MODEL_URL: ${{ secrets.AI_MODEL_URL }}

            # GEMINI
            GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
            GEMINI_MODEL: ${{ secrets.GEMINI_MODEL }}
            EOF
            
            git pull origin main
            
            docker-compose -f docker-compose.prod.yml down
            docker-compose -f docker-compose.prod.yml up -d