name: Database Migration

on:
  workflow_dispatch:
  push:
    paths:
      - 'cmd/database/migrate/**'
    branches:
      - main

jobs:
  migrate:
    name: Run Database Migration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Migrations
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /path/to/your/project
            docker-compose -f docker-compose.prod.yml exec -T app /app/db-cli -migrate